name: Multi-Agent Incident Response
enabled: true
triggers:
  - type: manual
  - type: webhook

inputs:
  - name: incident_description
    type: string
  - name: affected_service
    type: string
  - name: reported_severity
    type: string

steps:
  # =========================================================================
  # PHASE 1: DATA GATHERING (workflow-level, before any agent)
  # =========================================================================

  # Step 1: Percolate the incident against stored alert rules (reverse search)
  - name: check_alert_rules
    type: elasticsearch.search
    with:
      index: alert-rules
      query:
        percolate:
          field: query
          document:
            message: "{{ inputs.incident_description }}"
            service.name: "{{ inputs.affected_service }}"
            log.level: "ERROR"

  # Step 2: Get recent error counts for the affected service
  - name: recent_errors
    type: elasticsearch.esql
    with:
      query: >
        FROM logs-opsagent-*
        | WHERE service.name == "{{ inputs.affected_service }}"
          AND @timestamp > NOW() - 1 hour
          AND log.level IN ("ERROR", "FATAL")
        | STATS error_count = COUNT(*), last_error = MAX(@timestamp)
          BY error.type
        | SORT error_count DESC
        | LIMIT 10

  # Step 3: Get service owner information
  - name: get_service_owner
    type: elasticsearch.search
    with:
      index: service-owners
      query:
        term:
          service_name: "{{ inputs.affected_service }}"

  # =========================================================================
  # PHASE 2: TRIAGE AGENT -- First responder, severity classification
  # =========================================================================

  - name: triage_analysis
    type: ai.agent
    with:
      agent_id: triage-agent
      message: >
        INCIDENT TRIAGE REQUEST

        Service: {{ inputs.affected_service }}
        Reported severity: {{ inputs.reported_severity }}
        Description: {{ inputs.incident_description }}

        PRELIMINARY DATA (gathered by workflow):
        - Alert rules matched: {{ steps.check_alert_rules.output.hits.total.value }} rule(s)
        - Recent error types: {{ steps.recent_errors.output | json }}
        - Service owner: {{ steps.get_service_owner.output.hits.hits.0._source | json }}

        Please perform rapid triage:
        1. Search for similar past incidents using hybrid_rag_search.
        2. Analyze error trends for {{ inputs.affected_service }}.
        3. Get the error breakdown.
        4. Classify severity and recommend what the Investigation Agent should focus on.

  # =========================================================================
  # PHASE 3: INVESTIGATION AGENT -- Deep-dive root cause analysis
  # =========================================================================

  - name: investigation_analysis
    type: ai.agent
    with:
      agent_id: investigation-agent
      message: >
        INVESTIGATION REQUEST (handoff from Triage Agent)

        Service: {{ inputs.affected_service }}
        Description: {{ inputs.incident_description }}

        TRIAGE AGENT FINDINGS:
        {{ steps.triage_analysis.output.content }}

        ALERT RULES MATCHED (via percolate):
        {{ steps.check_alert_rules.output.hits.hits | json }}

        Please perform deep-dive investigation:
        1. Run significant_terms on logs-opsagent-* for {{ inputs.affected_service }} to find the ROOT CAUSE (statistically unusual errors).
        2. Run pipeline aggregations (derivative + moving_avg) to detect error ACCELERATION.
        3. Run percolate query on alert-rules to find ALL matching alert rules.
        4. Assess blast radius across related services.
        5. Provide root cause with confidence level and recommended remediation.

  # =========================================================================
  # PHASE 4: POSTMORTEM AGENT -- Synthesize findings into post-mortem
  # =========================================================================

  - name: postmortem_report
    type: ai.agent
    with:
      agent_id: postmortem-agent
      message: >
        POST-MORTEM GENERATION REQUEST

        Service: {{ inputs.affected_service }}
        Description: {{ inputs.incident_description }}
        Workflow execution: {{ execution.id }}

        TRIAGE AGENT FINDINGS:
        {{ steps.triage_analysis.output.content }}

        INVESTIGATION AGENT FINDINGS:
        {{ steps.investigation_analysis.output.content }}

        SERVICE OWNER:
        {{ steps.get_service_owner.output.hits.hits.0._source | json }}

        Please generate a complete blameless post-mortem:
        1. Search for prevention strategies from similar past incidents.
        2. Synthesize triage + investigation findings into a structured report.
        3. Include timeline, root cause, blast radius, and action items.

  # =========================================================================
  # PHASE 5: SEVERITY-BASED NOTIFICATION
  # =========================================================================

  # Extract severity from triage for routing
  - name: extract_severity
    type: ai.prompt
    with:
      prompt: >
        Extract ONLY the severity classification from this analysis.
        Respond with exactly one of: P1, P2, P3, P4. Nothing else.
        Analysis: {{ steps.triage_analysis.output.content }}

  # Send Slack notification with full multi-agent analysis
  - name: notify_slack
    type: slack
    with:
      channel: "{{ steps.get_service_owner.output.hits.hits.0._source.slack_channel | default: '#ops-alerts' }}"
      message: >
        *Multi-Agent Incident Response Alert*

        *Service:* {{ inputs.affected_service }}
        *Severity:* {{ steps.extract_severity.output.content }}
        *Alert Rules Matched:* {{ steps.check_alert_rules.output.hits.total.value }}

        *Triage Summary:*
        {{ steps.triage_analysis.output.content }}

        *Investigation Root Cause:*
        {{ steps.investigation_analysis.output.content }}

        *Post-Mortem:*
        {{ steps.postmortem_report.output.content }}

        *Owner:* {{ steps.get_service_owner.output.hits.hits.0._source.owner_team | default: 'unassigned' }}

  # Create Jira ticket for P1/P2
  - name: check_needs_jira
    type: if
    condition: "{{ steps.extract_severity.output.content contains 'P1' or steps.extract_severity.output.content contains 'P2' }}"
    steps:
      - name: create_jira_ticket
        type: jira
        with:
          project: "OPS"
          issue_type: "Incident"
          summary: "[{{ steps.extract_severity.output.content }}] {{ inputs.affected_service }} - {{ inputs.incident_description | truncate: 80 }}"
          description: >
            h2. Multi-Agent Incident Report

            *Service:* {{ inputs.affected_service }}
            *Severity:* {{ steps.extract_severity.output.content }}
            *Reported:* {{ execution.timestamp }}

            h3. Triage Agent Findings
            {{ steps.triage_analysis.output.content }}

            h3. Investigation Agent Findings
            {{ steps.investigation_analysis.output.content }}

            h3. Post-Mortem
            {{ steps.postmortem_report.output.content }}
          priority: "{{ steps.extract_severity.output.content == 'P1' | ternary: 'Highest', 'High' }}"
          assignee: "{{ steps.get_service_owner.output.hits.hits.0._source.owner_email }}"

  # =========================================================================
  # PHASE 6: AUDIT LOGGING
  # =========================================================================

  - name: log_incident
    type: elasticsearch.index
    with:
      index: opsagent-incident-log
      document:
        "@timestamp": "{{ execution.timestamp }}"
        incident_description: "{{ inputs.incident_description }}"
        affected_service: "{{ inputs.affected_service }}"
        reported_severity: "{{ inputs.reported_severity }}"
        classified_severity: "{{ steps.extract_severity.output.content }}"
        alert_rules_matched: "{{ steps.check_alert_rules.output.hits.total.value }}"
        triage_analysis: "{{ steps.triage_analysis.output.content }}"
        investigation_analysis: "{{ steps.investigation_analysis.output.content }}"
        postmortem_report: "{{ steps.postmortem_report.output.content }}"
        owner_team: "{{ steps.get_service_owner.output.hits.hits.0._source.owner_team }}"
        workflow_execution_id: "{{ execution.id }}"
        agents_used:
          - "triage-agent"
          - "investigation-agent"
          - "postmortem-agent"
